### ISSUE TITLE
Always returns one of the polygon vertices

### ISSUE THREAD

**Issue by ayushsubedi** [nyukhalov/polylabel-java#1]
nyukhalov, thank you for porting this to java. However, I tried performing this and unfortunately, it is only returning one of the input vertices. Is this a complete implementation?

**Comment by nyukhalov** [comment]
Hi @ayushsubedi, yes, this is a complete implementation.
Could you please share your input data so that I can reproduce the issue?

**Comment by ayushsubedi** [comment]
I retested my input,
Instead of creating the polygon rings in the following manner,


    protected static LatLng housePoleOfInaccessibility(List<Point> pointList){
        // The input param is a list of Point (com.mapbox.geojson.Point)
        // This Object is different to the Point object (com.mapbox.services.commons.geojson.Point) used in Polylabel
        List<List<Position>> rings = new ArrayList<>();
        List<Position> outer_ring = new ArrayList<>();
    
        // Creating outer ring
        for (int i=0; i<pointList.size()-1; i++){
            outer_ring.add(Position.fromCoordinates(pointList.get(i).latitude(), pointList.get(i).longitude()));
        }
    
        // Not concerned about inner ring
        // Polylabel also uses the 0 index (outer ring)
        rings.add(outer_ring);
        ...

I was creating them incorrectly,

    protected static LatLng housePoleOfInaccessibility(List<Point> pointList){
          // The input param is a list of Point (com.mapbox.geojson.Point)
        // This Object is different to the Point object (com.mapbox.services.commons.geojson.Point) used in Polylabel
            List<List<Position>> rings = new ArrayList<>();
            // Creating outer ring
            for (int i=0; i<pointList.size()-1; i++){
                rings.add(Collections.singletonList(Position.fromCoordinates(pointList.get(i).latitude(), pointList.get(i).longitude())));
            }

Thanks again. It works like a charm.
